# Generated by Django 4.0.6 on 2022-07-31 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_general', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcription',
            old_name='registered',
            new_name='registered_at',
        ),
    ]
