# Generated by Django 4.0.6 on 2022-07-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_foods', '0003_alter_foodmodel_end_promotion'),
        ('App_general', '0002_rename_registered_subcription_registered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcription',
            name='food_set',
            field=models.ManyToManyField(to='App_foods.foodmodel'),
        ),
    ]
