# Generated by Django 4.0.6 on 2022-07-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='foodmodel',
            name='special_Price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='is_Premium',
            field=models.BooleanField(default=False),
        ),
    ]
