# Generated by Django 4.0.6 on 2022-07-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_foods', '0002_foodmodel_description_foodmodel_special_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmodel',
            name='end_Promotion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
