# Generated by Django 4.1 on 2022-08-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_foods', '0003_alter_foodmodel_end_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmodel',
            name='image_relative_url',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodmodel',
            name='special_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
